# Generated by Django 2.2.6 on 2023-04-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObsceneWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obscene_word', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('political_word', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
