# Generated by Django 2.2.6 on 2023-04-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsceneLang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obsceneword',
            name='comments',
            field=models.TextField(blank=True, max_length=75, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='politicalword',
            name='comments',
            field=models.TextField(blank=True, max_length=75, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='obsceneword',
            name='obscene_word',
            field=models.CharField(max_length=30, unique=True, verbose_name='Нецензурные слова'),
        ),
        migrations.AlterField(
            model_name='politicalword',
            name='political_word',
            field=models.CharField(max_length=30, unique=True, verbose_name='Неполиткорректные слова'),
        ),
    ]
