# Generated by Django 2.2.6 on 2023-04-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsceneLang', '0002_auto_20230419_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_word', models.CharField(max_length=50, unique=True, verbose_name='Нецензурное слово')),
                ('word_type', models.CharField(max_length=50, verbose_name='Тип слова')),
                ('comments', models.TextField(blank=True, max_length=75, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Запрещенное слово',
                'verbose_name_plural': 'Запрещенные слова',
                'ordering': ('banned_word',),
            },
        ),
        migrations.DeleteModel(
            name='ObsceneWord',
        ),
        migrations.DeleteModel(
            name='PoliticalWord',
        ),
    ]
