# Generated by Django 2.2.16 on 2023-04-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsceneLang', '0003_auto_20230421_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannedword',
            name='banned_word',
            field=models.CharField(max_length=50, unique=True, verbose_name='Запрещенное слово'),
        ),
    ]
