# Generated by Django 2.2.16 on 2023-04-27 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsceneLang', '0004_auto_20230423_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannedword',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(75)], verbose_name='Комментарий'),
        ),
    ]
